const GENRE_EN: Record<number, string> = {
  1: "Action",
  2: "Adventure",
  3: "Comedy",
  4: "Drama",
  5: "Fantasy",
  6: "Horror",
  7: "Mystery",
  8: "Romance",
  9: "Sci-Fi",
  10: "Slice of Life",
  11: "Sports",
  12: "Supernatural",
  13: "Thriller",
  14: "Mecha",
  15: "Music",
  16: "Psychological",
  17: "Historical",
  18: "Military",
  19: "Parody",
  20: "Martial Arts",
  21: "Shounen",
  22: "Shoujo",
  23: "Seinen",
  24: "Josei",
  25: "Isekai",
  26: "Game",
  27: "Detective",
  28: "Work",
  29: "Magic",
  30: "Vampires",
  31: "Samurai",
  32: "Cars",
  33: "Demons",
  34: "Space",
  35: "Kids",
  36: "Police",
  37: "Harem",
  38: "Super Power",
  39: "Ecchi",
  40: "Yaoi",
  41: "Yuri",
  42: "Reverse Harem",
  43: "Shounen Ai",
  44: "Shoujo Ai",
  45: "Doujinshi",
  46: "Gender Bender",
  47: "Cooking",
  48: "Mahou Shoujo",
  49: "School",
  50: "Romantic Comedy",
  51: "Tragedy",
  52: "Post-Apocalyptic",
  53: "Survival",
  54: "Time Travel",
  55: "Virtual Reality",
  56: "Romantic Comedy",
  57: "Anthology",
  58: "Gag Humor",
  59: "Everyday Life",
  60: "Mythology",
  61: "Biology",
  62: "Philosophy",
  63: "Social Commentary",
  64: "Delinquents",
  65: "Office",
  66: "Ninja",
  67: "Robots",
  68: "Cyberpunk",
  69: "Steampunk",
  70: "Campus",
  71: "Love Triangle",
  72: "War",
  73: "Strategy",
  74: "Athletics",
  75: "Occult",
  76: "Idols",
  77: "Otaku",
  78: "Anthropomorphism",
  79: "CGDCT",
  80: "Reincarnation",
};

export function getGenreName(
  genre: { id: number; name: string },
  language: "ru" | "en",
): string {
  if (language === "en") {
    return GENRE_EN[genre.id] ?? genre.name;
  }
  return genre.name;
}
